Documentation style guide
nebari-dev/nebari-docs pull request #172
Opened 2022-10-07 10:21 UTC by pavithraes

## Reference Issues or PRs

## What does this implement/fix?

_Put an `x` in the boxes that apply_

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds a feature)
- [ ] Breaking change (fix or feature that would cause existing features to not work as expected)
- [ ] Documentation Update
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build related changes
- [ ] Other (please describe):

## Testing

- [ ] Did you test the pull request locally?
- [ ] Did you add new tests?

## Documentation

### Access-centered content checklist

#### Text styling

- [ ] The content is written with [plain language](https://www.plainlanguage.gov/guidelines/) (where relevant).
- [ ] If there are headers, they use the proper header tags (with only one level-one header: `H1` or `#` in markdown).
- [ ] All links describe where they link to (for example, check the [Nebari website](https://nebari.dev/)).
- [ ] This content adheres to the Nebari style guides.

#### Non-text content

- [ ] All content is represented as text (for example, images need alt text, and videos need captions or descriptive transcripts).
- [ ] If there are emojis, there are not more than three in a row.
- [ ] Don't use [flashing GIFs or videos](https://www.w3.org/TR/UNDERSTANDING-WCAG20/seizure-does-not-violate.html).
- [ ] If the content were to be read as plain text, it still makes sense, and no information is missing.

### Any other comments?

2022-10-10 13:46 UTC, pavithraes commented on docs/docs/community/style-guide.md
> +
```suggestion

These are not rules, they are suggestions. Follow your best judgment and feel free to add to this document!

```

2022-10-10 13:51 UTC, pavithraes commented on docs/docs/community/style-guide.md
> +
```suggestion

These are not rules, they are suggestions. Follow your best judgment and feel free to add to this document!

```

2022-10-12 11:01 UTC, trallard requested changes
This looks excellent @pavithraes - left some suggestions and notes, but otherwise this seems so close to merge 🚀 🌻

2022-10-12 11:05 UTC, pavithraes commented on docs/docs/community/style-guide.md
> +
Thank you!

2022-10-12 11:12 UTC, pavithraes commented on docs/docs/community/style-guide.md
> +
I see it's always lowercase in our docs + branding material, so I'll go with that. I'll also make sure to confirm with Dharhas and Pierre. :)

2022-10-12 11:59 UTC, trallard approved these changes
Perfect! Merging

2022-10-12 11:59 UTC, merged