Migrating old Argo docs and applying minor updates
nebari-dev/nebari-docs pull request #268
Opened 2023-02-02 19:08 UTC by kcpevey

This PR migrates over the old Argo docs and also provides some updates that are coming from PR https://github.com/nebari-dev/nebari/pull/1639 .

## Reference Issues or PRs

## What does this implement/fix?

_Put a `x` in the boxes that apply_

- [x] Documentation Update

## Testing

- [x] Did you test the pull request locally?

## Documentation

### Access-centered content checklist

#### Text styling

- [ ] The content is written with [plain language](https://www.plainlanguage.gov/guidelines/) (where relevant).
- [ ] If there are headers, they use the proper header tags (with only one level-one header: `H1` or `#` in markdown).
- [ ] All links describe where they link to (for example, check the [Nebari website](https://nebari.dev/)).
- [ ] This content adheres to the Nebari style guides.

#### Non-text content

- [x] All content is represented as text (for example, images need alt text, and videos need captions or descriptive transcripts).
- [x] If there are emojis, there are not more than three in a row.
- [x] Don't use [flashing GIFs or videos](https://www.w3.org/TR/UNDERSTANDING-WCAG20/seizure-does-not-violate.html).
- [x] If the content were to be read as plain text, it still makes sense, and no information is missing.

## Any other comments?

2023-03-09 15:04 UTC, pavithraes commented on docs/docs/tutorials/using-argo.md
> +title: Automating workflows with Argo
```suggestion
title: Automate workflows with Argo
```

2023-03-09 15:05 UTC, pavithraes commented on docs/docs/tutorials/using-argo.md
> +# Argo Workflows
```suggestion
# Automate workflows with Argo
```

2023-03-09 15:06 UTC, pavithraes commented on docs/docs/tutorials/using-argo.md
> +## Accessing Argo Server
```suggestion
## Access Argo Server
```

2023-03-09 15:06 UTC, pavithraes commented on docs/docs/tutorials/using-argo.md
> +## Submitting a Workflow via Argo Server
```suggestion
## Submit a workflow via Argo Server
```

2023-03-09 15:06 UTC, pavithraes commented on docs/docs/tutorials/using-argo.md
> +## Submitting a workflow via Argo CLI
```suggestion
## Submit a workflow via Argo CLI
```

2023-03-09 15:07 UTC, pavithraes commented on docs/docs/how-tos/setup-argo.md
> +title: Setting up Argo Workflows
```suggestion
title: Set up Argo Workflows
```

2023-03-09 15:08 UTC, pavithraes commented on docs/docs/how-tos/setup-argo.md
> +# Argo Workflows
```suggestion
# Set up Argo workflows
```

2023-03-09 15:08 UTC, pavithraes commented on docs/docs/how-tos/setup-argo.md
> +## Accessing Argo Server
```suggestion
## Access Argo Server
```

2023-03-09 15:08 UTC, pavithraes commented on docs/docs/how-tos/setup-argo.md
> +## Disabling Argo Workflows
```suggestion
## Disable Argo Workflows
```

2023-03-09 15:11 UTC, pavithraes requested changes
@kcpevey Thank you for working on this, it looks good to me. 

I've mainly just added style-guide-related suggestions for consistency. Other than that, I think the `using-argo.md` can be moved to the how-tos section -- mainly because I think tutorials are intended to be to complete end-to-end examples? What do you think?

I do agree that we can merge this migrating PR and make updates as we go. :)

2023-03-22 14:58 UTC, kcpevey commented
@pavithraes your requested changes have been made. This is ready for final review and merge!

2023-03-28 11:27 UTC, merged