Add docs for deploying nebari on existing k8s
nebari-dev/nebari-docs pull request #300
Opened 2023-04-13 20:12 UTC by viniciusdc

## Reference Issues or PRs
closes #256 

## What does this implement/fix?

_Put a `x` in the boxes that apply_

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds a feature)
- [ ] Breaking change (fix or feature that would cause existing features not to work as expected)
- [ ] Documentation Update
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build related changes
- [ ] Other (please describe):

## Testing

- [ ] Did you test the pull request locally?
- [ ] Did you add new tests?

## Documentation

### Access-centered content checklist

#### Text styling

- [ ] The content is written with [plain language](https://www.plainlanguage.gov/guidelines/) (where relevant).
- [ ] If there are headers, they use the proper header tags (with only one level-one header: `H1` or `#` in markdown).
- [ ] All links describe where they link to (for example, check the [Nebari website](https://nebari.dev/)).
- [ ] This content adheres to the Nebari style guides.

#### Non-text content

- [ ] All content is represented as text (for example, images need alt text, and videos need captions or descriptive transcripts).
- [ ] If there are emojis, there are not more than three in a row.
- [ ] Don't use [flashing GIFs or videos](https://www.w3.org/TR/UNDERSTANDING-WCAG20/seizure-does-not-violate.html).
- [ ] If the content were to be read as plain text, it still makes sense, and no information is missing.

## Any other comments?

2023-04-18 19:14 UTC, iameskild requested changes
This is looking great @viniciusdc! I just made one minor update 👍

2023-04-18 19:14 UTC, iameskild commented on docs/docs/how-tos/nebari-kubernets.mdx
> +provider: local
```suggestion
provider: existing
```

2023-04-24 15:46 UTC, iameskild approved these changes
Thanks @viniciusdc :)

2023-04-24 15:49 UTC, iameskild submitted a review, later dismissed
Sorry for the premature approval... I have one more comment and I think @pavithraes wants to make sure we update any cross reference link as well 👍

2023-05-02 18:15 UTC, viniciusdc commented on docs/docs/how-tos/nebari-kubernets.mdx
> +    This is the custom configuration for GCP
Thanks @iameskild, I removed the mentions of GCP of now, once we had that tested we can include it

2023-05-02 18:16 UTC, viniciusdc commented
Hi @pavithraes, I just updated the reference in the get-started, it would be great if you could do a last look into that

2023-05-03 09:07 UTC, pavithraes approved these changes
Looks great, thanks Vini!

2023-05-03 09:08 UTC, merged