Add docs for installing and setup kubectl
nebari-dev/nebari-docs pull request #315
Opened 2023-04-25 00:28 UTC by viniciusdc

## Reference Issues or PRs

closes #314 

## What does this implement/fix?

_Put a `x` in the boxes that apply_

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds a feature)
- [ ] Breaking change (fix or feature that would cause existing features not to work as expected)
- [ ] Documentation Update
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build related changes
- [ ] Other (please describe):

## Testing

- [ ] Did you test the pull request locally?
- [ ] Did you add new tests?

## Documentation

### Access-centered content checklist

#### Text styling

- [ ] The content is written with [plain language](https://www.plainlanguage.gov/guidelines/) (where relevant).
- [ ] If there are headers, they use the proper header tags (with only one level-one header: `H1` or `#` in markdown).
- [ ] All links describe where they link to (for example, check the [Nebari website](https://nebari.dev/)).
- [ ] This content adheres to the Nebari style guides.

#### Non-text content

- [ ] All content is represented as text (for example, images need alt text, and videos need captions or descriptive transcripts).
- [ ] If there are emojis, there are not more than three in a row.
- [ ] Don't use [flashing GIFs or videos](https://www.w3.org/TR/UNDERSTANDING-WCAG20/seizure-does-not-violate.html).
- [ ] If the content were to be read as plain text, it still makes sense, and no information is missing.

## Any other comments?

2023-04-25 15:48 UTC, Adam-D-Lewis commented on docs/docs/how-tos/debug-nebari.mdx
> +Generally, it does not mean that there will be a file named kubeconfig present in you machine.
typo: "you machine" should be "your machine"

2023-04-25 15:55 UTC, Adam-D-Lewis requested changes
I have a few small suggestions, but it looks great overall.

2023-04-26 00:38 UTC, viniciusdc commented on docs/docs/how-tos/debug-nebari.mdx
> -You can skip to the [Getting started with k9s](#getting-started-with-k9s) below.
I might be wrong on this, but my current understanding is that nebari will auto-generate the kubeconfig file during deployment, for example on GCP
https://github.com/nebari-dev/nebari/blob/1cef576e673e8e0cda9aac4bbe769302cf846c42/nebari/template/stages/02-infrastructure/gcp/outputs.tf#L11-L21

2023-04-27 14:17 UTC, Adam-D-Lewis approved these changes

2023-04-27 14:19 UTC, merged