Add docs for `helm_extension` mechanism
nebari-dev/nebari-docs pull request #402
Opened 2024-01-22 15:19 UTC by viniciusdc

## Reference Issues or PRs

## What does this implement/fix?

Includes doc section for helm_extension mechanism that was added as part of https://github.com/nebari-dev/nebari/issues/865

_Put a `x` in the boxes that apply_

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds a feature)
- [ ] Breaking change (fix or feature that would cause existing features not to work as expected)
- [x] Documentation Update
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build related changes
- [ ] Other (please describe):

## Testing

- [ ] Did you test the pull request locally?
- [ ] Did you add new tests?

## Documentation

### Access-centered content checklist

#### Text styling

- [ ] The content is written with [plain language](https://www.plainlanguage.gov/guidelines/) (where relevant).
- [ ] If there are headers, they use the proper header tags (with only one level-one header: `H1` or `#` in markdown).
- [ ] All links describe where they link to (for example, check the [Nebari website](https://nebari.dev/)).
- [ ] This content adheres to the Nebari style guides.

#### Non-text content

- [ ] All content is represented as text (for example, images need alt text, and videos need captions or descriptive transcripts).
- [ ] If there are emojis, there are not more than three in a row.
- [ ] Don't use [flashing GIFs or videos](https://www.w3.org/TR/UNDERSTANDING-WCAG20/seizure-does-not-violate.html).
- [ ] If the content were to be read as plain text, it still makes sense, and no information is missing.

## Any other comments?

**Maybe this is already in the docs, and I just didn't find it; if that's the case, feel free to close it.

2024-04-02 15:16 UTC, marcelovilla requested changes

2024-04-02 15:16 UTC, marcelovilla commented on docs/docs/explanations/advanced-custom-settings.md
> +Nebari provides a way for any user to expand the infrastructure availablke by default by using the `helm_extensions` attribute, which allows for the management and customization of Kubernetes applica
There's a typo on available

2024-05-14 16:17 UTC, marcelovilla approved these changes
LGTM! Thanks @viniciusdc!

2024-07-26 14:01 UTC, viniciusdc commented on docs/docs/explanations/advanced-custom-settings.md
> +:::
```suggestion
```

2024-07-26 14:02 UTC, viniciusdc commented on docs/docs/explanations/advanced-custom-settings.md
>  ```
```suggestion
```

:::note Note
Current `conda_store.worker_resources` defaults are set at the minimum recommended resources for conda-store-workers - (conda-store [docs](https://conda.store/conda-store/references/faq#what-are-the-resource-requirements-for-conda-store-server))
:::
```

2024-08-06 14:25 UTC, merged