438 services menu improvements
nebari-dev/nebari-docs pull request #466
Opened 2024-05-24 20:09 UTC by pt247

## Reference Issues or PRs

Fixes #438

## What does this implement/fix?
Updates https://www.nebari.dev/docs/tutorials/login-keycloak/ page. 

_Put a `x` in the boxes that apply_

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds a feature)
- [ ] Breaking change (fix or feature that would cause existing features not to work as expected)
- [x] Documentation Update
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build related changes
- [ ] Other (please describe):

## Testing

- [x] Did you test the pull request locally?
- [ ] Did you add new tests?

## Documentation

### Access-centered content checklist

#### Text styling

- [ ] The content is written with [plain language](https://www.plainlanguage.gov/guidelines/) (where relevant).
- [ ] If there are headers, they use the proper header tags (with only one level-one header: `H1` or `#` in markdown).
- [ ] All links describe where they link to (for example, check the [Nebari website](https://nebari.dev/)).
- [ ] This content adheres to the Nebari style guides.

#### Non-text content

- [ ] All content is represented as text (for example, images need alt text, and videos need captions or descriptive transcripts).
- [ ] If there are emojis, there are not more than three in a row.
- [ ] Don't use [flashing GIFs or videos](https://www.w3.org/TR/UNDERSTANDING-WCAG20/seizure-does-not-violate.html).
- [ ] If the content were to be read as plain text, it still makes sense, and no information is missing.

## Any other comments?

2024-05-28 10:22 UTC, pt247 commented
@kcpevey I have updated the page. Please compare [updated](https://deploy-preview-466--nebari-docs.netlify.app/docs/tutorials/login-keycloak) and [existing](https://www.nebari.dev/docs/tutorials/login-keycloak/).

2024-05-28 19:46 UTC, kcpevey requested changes
Apologies, I wasn't very clear. I'd like the event log warning message to be included at the top level, not inside the hidden expandable section.

2024-05-28 19:46 UTC, kcpevey commented on docs/docs/tutorials/login-with-keycloak.md
> +
```suggestion
```

2024-05-28 19:46 UTC, kcpevey commented on docs/docs/tutorials/login-with-keycloak.md
>  :::
```suggestion
:::warning
- The starting up sequence can take up to several minutes, depending on the size of the cluster. If the server is not accessible **after 10 minutes**, an error will be shown, and you will be redirected to the Home page. Please check the [troubleshooting docs][troubleshooting] for more information.

- The Event logs may include warnings about `"[Warning] 0/2 nodes are available: 2 node(s) didn't match Pod's node affinity/selector ..." `. This is normal behaviour as cluster sometimes need to expand in order to start the server.
- Warning such as `"[Warning]" Unable to retrieve some image pull secrets ..."` can also be safely ignored.
:::
```

2024-05-29 09:28 UTC, pt247 commented on docs/docs/tutorials/login-with-keycloak.md
>  :::
It makes sense.  Done.

2024-05-29 12:57 UTC, viniciusdc commented on docs/static/img/tutorials/nebari-home.png
Hi @pt247, I will rename those custom apps below (trame ones) to something like `app`. Could you then retake the print?

2024-05-29 14:35 UTC, pt247 commented on docs/static/img/tutorials/nebari-home.png
Done.

2024-05-29 15:55 UTC, viniciusdc commented on docs/docs/explanations/advanced-custom-settings.md
@pt247 I see that you already included the keda config section in here, I would like to merge it after the corresponding code is also merged in nebari. But, to not block this one, can you move this changes to a separate PR?

2024-05-29 15:57 UTC, viniciusdc commented
Besides the point above, all LGTM. @kcpevey is there anything else you would like to include as part of this?

2024-06-04 18:04 UTC, kcpevey approved these changes
LGTM. Thanks @pt247 !

2024-06-04 18:22 UTC, merged