Loki doc updates
nebari-dev/nebari-docs pull request #491
Opened 2024-07-30 19:38 UTC by kenafoster

## Reference Issues or PRs
https://github.com/nebari-dev/nebari-docs/issues/442

## What does this implement/fix?

_Put a `x` in the boxes that apply_

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds a feature)
- [ ] Breaking change (fix or feature that would cause existing features not to work as expected)
- [X ] Documentation Update
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build related changes
- [ ] Other (please describe):

## Testing

- [ ] Did you test the pull request locally?
- [ ] Did you add new tests?

## Documentation

### Access-centered content checklist

#### Text styling

- [ ] The content is written with [plain language](https://www.plainlanguage.gov/guidelines/) (where relevant).
- [ ] If there are headers, they use the proper header tags (with only one level-one header: `H1` or `#` in markdown).
- [ ] All links describe where they link to (for example, check the [Nebari website](https://nebari.dev/)).
- [ ] This content adheres to the Nebari style guides.

#### Non-text content

- [ ] All content is represented as text (for example, images need alt text, and videos need captions or descriptive transcripts).
- [ ] If there are emojis, there are not more than three in a row.
- [ ] Don't use [flashing GIFs or videos](https://www.w3.org/TR/UNDERSTANDING-WCAG20/seizure-does-not-violate.html).
- [ ] If the content were to be read as plain text, it still makes sense, and no information is missing.

## Any other comments?

2024-07-31 18:51 UTC, kcpevey commented
This page is really directed at the sys admin user who manages deployments. I actually think the page needs to be renamed "How to setup monitoring on Nebari". Then, a separate page would show "How to access system logs (Loki) via Grafana" - which would walk folks how to actually get to the logs. 

In particular, I'd like to understand what each of the labels mean 

![image](https://github.com/user-attachments/assets/f6375891-1b9e-4e4a-b307-e23a2f044292)

Under each of those labels, there is a variety of values. I'd like to understand (at a very high level) what each of those are (or at least the subtypes, e.g. `hub-{somehash}`)

2024-08-01 16:32 UTC, viniciusdc commented
> Under each of those labels, there is a variety of values. I'd like to understand (at a very high level) what each of those are (or at least the subtypes, e.g. hub-{somehash})

I think it would benefit or linkig to https://grafana.com/docs/loki/latest/query/log_queries/ for an overview of how to write and understand the querying structure, and https://grafana.com/docs/grafana/latest/datasources/loki/query-editor/#choose-a-query-editing-mode for how the editor works. Also, you can get a gist of some of the "labels" there here https://kubernetes.io/docs/reference/glossary/?workload=true, it usually means what type of resource present in you k8s cluster you can target and filter logs from.

2024-08-07 17:12 UTC, kcpevey requested changes
@kenafoster I've review the `access-logs-loki` doc here, but I need to add an image and extra text to the setup doc so rather work through suggested changes, I'll just push changes.

2024-08-07 17:12 UTC, kcpevey commented on docs/docs/how-tos/access-logs-loki.md
> +
```suggestion
```

moving these to the bottom on this list

2024-08-07 17:12 UTC, kcpevey commented on docs/docs/how-tos/access-logs-loki.md
> +
```suggestion
### Deployed app logs (via jhub-apps)

If you have `jhub-apps` enabled on your deployment can you view the logs to debug deployed apps. 

To see the logs from **all deployed apps**, use the label filter `container` = `notebook`. The main container in each deployed app pod is named `notebook`.

To see **logs from a specific app**, use the `pod` label and begin typing either the name of the user running the app or the app name to find the correct pod.  App pods are named with the convention `jupyter-[username]--[app_name]-[pod_id]`.
```

2024-08-07 18:53 UTC, viniciusdc commented on docs/docs/how-tos/setup-monitoring.md
> +For details on how to view specific logs in Loki, check out the document ["How to access system logs via Grafana"](access-logs-loki)
```suggestion
:::note
Loki's "labels" are used to filter collections of logs from the available [kubernetes_sd](https://grafana.com/docs/loki/latest/send-data/promtail/configuration/#kubernetes_sd_config) API endpoints, in a similar way as to how Prometheus handles metrics. These labels are configured through Promtail, which is the agent responsible for collecting and shipping logs to Loki, based on the defined [targets](https://grafana.com/docs/loki/latest/send-data/promtail/configuration/#scrape_configs) and scraping configurations.
:::

For details on how to view specific logs in Loki, check out the document ["How to access system logs via Grafana"](access-logs-loki)
```

2024-08-07 19:47 UTC, kcpevey commented on docs/docs/how-tos/monitoring.md
> +for JupyterHub pod:
I'm still wondering about this - if all users dont have access to this, then we should rework this example

2024-08-07 21:37 UTC, kenafoster commented on docs/docs/how-tos/monitoring.md
> +for JupyterHub pod:
Sorry missed this first go-around.  The only users who have access to this in Nebari's out-of-the-box configuration are those in the 'admin' keycloak group (these settings can be changed).

To me, reworking probably means just add note like:

The Explore functionality is only available to users who have `grafana_admin` permissions - a `grafana` client role in Keycloak.  In Nebari's default configuration, users in the `admin` user group will have this role.

2024-08-08 14:30 UTC, kcpevey commented on docs/docs/how-tos/monitoring.md
> +for JupyterHub pod:
ok thanks, can you add that note?

2024-08-08 18:15 UTC, kenafoster commented on docs/docs/how-tos/monitoring.md
> +for JupyterHub pod:
Yep - added!

2024-08-09 14:43 UTC, kcpevey approved these changes
Thanks @kenafoster! This looks great. Thanks for your patience on this!

2024-08-09 14:43 UTC, merged