Document inotify config for kind deployments
nebari-dev/nebari-docs pull request #496
Opened 2024-08-06 22:24 UTC by asmacdo

Fixes #495

## What does this implement/fix?

_Put a `x` in the boxes that apply_

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds a feature)
- [ ] Breaking change (fix or feature that would cause existing features not to work as expected)
- [X] Documentation Update
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build related changes
- [ ] Other (please describe):

## Documentation

### Access-centered content checklist

#### Text styling

- [X] The content is written with [plain language](https://www.plainlanguage.gov/guidelines/) (where relevant).
- [X] If there are headers, they use the proper header tags (with only one level-one header: `H1` or `#` in markdown).
- [X] All links describe where they link to (for example, check the [Nebari website](https://nebari.dev/)).
- [X] This content adheres to the Nebari style guides.

2024-09-23 17:09 UTC, kcpevey requested changes
Hi @asmacdo! Thank you for this contribution! I had a few minor changes to request.

2024-09-23 17:09 UTC, kcpevey commented on docs/docs/how-tos/nebari-local.md
> +
Can you also add the fixer snippet that you listed in the issue? I think that would be beneficial.

```
sudo sysctl fs.inotify.max_user_watches=524288      
sudo sysctl fs.inotify.max_user_instances=512
```

2024-09-23 17:09 UTC, kcpevey commented on docs/docs/how-tos/nebari-local.md
> +`fs.inotify.max_user_instances kernel parameters` if you see a `too many open files` in the logs of
```suggestion
`fs.inotify.max_user_instances kernel parameters` if you see the error "too many open files" in the logs of
```
The syntax highlighting on the error message being the same as the config variables was confusing to read so I switched it up.

2024-09-23 17:09 UTC, kcpevey commented on docs/docs/how-tos/nebari-local.md
> +docs](https://kind.sigs.k8s.io/docs/user/known-issues/#pod-errors-due-to-too-many-open-files)
```suggestion
docs](https://kind.sigs.k8s.io/docs/user/known-issues/#pod-errors-due-to-too-many-open-files) for more information.
```

2024-10-30 08:59 UTC, marcelovilla commented
@kcpevey can you give this another look so we get it over the finish line? Thanks!

2024-10-30 21:40 UTC, kcpevey approved these changes
@marcelovilla this looks good on my end

2024-10-30 23:04 UTC, marcelovilla commented
Thanks @asmacdo for your contribution and @kcpevey for your review!

2024-10-30 23:04 UTC, merged