Remove DigitalOcean references in the docs
nebari-dev/nebari-docs pull request #544
Opened 2024-11-18 08:22 UTC by marcelovilla

## Reference Issues or PRs
This is a companion docs PR for https://github.com/nebari-dev/nebari/pull/2838 and is related to issue https://github.com/nebari-dev/nebari/issues/2749

## What does this implement/fix?

_Put a `x` in the boxes that apply_

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds a feature)
- [ ] Breaking change (fix or feature that would cause existing features not to work as expected)
- [x] Documentation Update
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build related changes
- [ ] Other (please describe):

## Testing

- [ ] Did you test the pull request locally?
- [ ] Did you add new tests?

## Documentation

### Access-centered content checklist

#### Text styling

- [ ] The content is written with [plain language](https://www.plainlanguage.gov/guidelines/) (where relevant).
- [ ] If there are headers, they use the proper header tags (with only one level-one header: `H1` or `#` in markdown).
- [ ] All links describe where they link to (for example, check the [Nebari website](https://nebari.dev/)).
- [ ] This content adheres to the Nebari style guides.

#### Non-text content

- [ ] All content is represented as text (for example, images need alt text, and videos need captions or descriptive transcripts).
- [ ] If there are emojis, there are not more than three in a row.
- [ ] Don't use [flashing GIFs or videos](https://www.w3.org/TR/UNDERSTANDING-WCAG20/seizure-does-not-violate.html).
- [ ] If the content were to be read as plain text, it still makes sense, and no information is missing.

## Any other comments?

2024-11-18 08:25 UTC, marcelovilla commented
We still need to update https://github.com/nebari-dev/nebari-docs/blob/76fe01cf96a29752dbc2ecbb1a1d5a57affc36ab/docs/static/img/welcome/nebari_overview_sequence.png to remove the DigitalOcean logo

2024-11-18 12:27 UTC, dcmcand requested changes
Looks like a missed reference on:

https://github.com/nebari-dev/nebari-docs/blob/77281095c9c598f7504bfd0ecff9ad1a2d8c6335/docs/docs/explanations/advanced-configuration.md?plain=1#L268

and 

https://github.com/nebari-dev/nebari-docs/blob/77281095c9c598f7504bfd0ecff9ad1a2d8c6335/docs/docs/get-started/deploy.mdx?plain=1#L32

Also, I am guessing this would be in the release notes, but we should have a note explaining why digital ocean is gone.

2024-11-18 18:36 UTC, marcelovilla commented
@dcmcand thanks for the review and for catching those lingering references.

> Also, I am guessing this would be in the release notes, but we should have a note explaining why digital ocean is gone.

Correct. I think we should add a note to the release notes explaining this and adding an alternative for users that might still want to use Nebari in DigitalOcean (i.e., using the `existing` option)

2024-12-12 16:20 UTC, viniciusdc approved these changes

2024-12-15 18:55 UTC, dcmcand approved these changes

2024-12-16 12:07 UTC, merged