[DOC] Adding architecture documentation to explanations
nebari-dev/nebari-docs pull request #59
Opened 2022-06-23 14:00 UTC by costrouc

Closes #11 
Closes #27 
Closes #28 
Closes #29 
Closes #30 
Closes #31

This is still a work in progress.

2022-07-01 12:56 UTC, kcpevey commented on docs/docs/explanations/architecture.md
> +the Kubernetes cluster. All of the infrastructure diagrams before
i'm beginning to realize maybe you meant the diagrams were ready for review, not the PR itself...

2022-07-01 12:56 UTC, kcpevey commented on docs/docs/explanations/architecture.md
> +effort being put into networking. An EKS managed kubernetes cluster is
also inconsistency on capitalization of kubernetes.

2022-07-01 12:58 UTC, kcpevey commented on docs/docs/references/architecture.md
> +`destroy` infrastructure and kubernetes resources via [Terraform](https://www.terraform.io/). The `destroy` command roughly does the `deploy` command in reverse.
```suggestion
The `destroy` command roughly does the `deploy` command in reverse.
```

2022-07-01 13:02 UTC, kcpevey submitted a review, later dismissed

2022-09-06 13:10 UTC, trallard commented
ping @costrouc  - there are changes requested. Also, where are we up to with the new architecture diagrams?

2022-10-11 21:48 UTC, viniciusdc commented on docs/docs/explanations/architecture.md
> +network. Similar to all other deployments auto-scaling is enabled. A
I will redo all text contents, but answering your question is more to the first option: We deploy a managed Kubernetes, and its not within a virtual network

2022-10-11 21:49 UTC, viniciusdc commented
@kcpevey I will mark your suggestions above as "resolved" as I plan to re-write everything, I will keep them in mind though.

2022-10-17 05:58 UTC, aktech commented on docs/docs/explanations/architecture.mdx
> +to ensure security, redundancy and scalability
full stop after "scalability"

2022-10-17 05:58 UTC, aktech commented on docs/docs/explanations/architecture.mdx
> +Kubernetes is a powerful open-source system, initially developed by Google,
"open-source system" -> "open-source container orchestration system"

2022-10-17 05:58 UTC, aktech commented on docs/docs/explanations/architecture.mdx
> +for managing containerized applications in a clustered environment. It aims
Not sure if "clustered environment" is a commonly used term. I would suggest `cluster` instead.

2022-10-17 05:58 UTC, aktech commented on docs/docs/explanations/architecture.mdx
> +Kubernetes provides fine-grained control in applications and container lifecycles,
control -> controls

2022-10-17 05:58 UTC, aktech commented on docs/docs/explanations/architecture.mdx
> +especially in dynamic environments. Tasks such as pod tracking, availability, and
I wouldn't write "pod tracking" here. We're explaining Kubernetes here and assuming people would know what's a pod is probably not a good idea and "pod tracking" isn't really a popular term anyway.

2022-12-06 12:35 UTC, trallard commented
@costrouc what is needed to move this PR forward? it has been in progress for a while and it would be great to add it to the docs ASAP

2022-12-14 16:28 UTC, kcpevey commented
It was originally owned by @costrouc, then @viniciusdc took over. It definitely needs to be merged ASAP.

2022-12-14 16:54 UTC, viniciusdc commented
Based on what has been discussed so far and the reviews. We could avoid describing the diagrams in detail (no details at all for now) and refactor the page layout to show the images. We can then have another issue to update them at a later time. This way, we can move forward with this.

Currently, the missing thing on this is that we only added the images but did not explain where these resources are used or how they are used (a.ka Jupyterlab pods are initiated by a user trigger that spawns a Pod with the requested resources.... and is scaled down once idle)

2022-12-14 16:54 UTC, viniciusdc commented
> It was originally owned by @costrouc, then @viniciusdc took over. It definitely needs to be merged ASAP.

Based on what has been discussed so far and the reviews. We could avoid describing the diagrams in detail (no details at all for now) and refactor the page layout to show the images. We can then have another issue to update them at a later time. This way, we can move forward with this.

Currently, the missing thing on this is that we only added the images but did not explain where these resources are used or how they are used (a.ka Jupyterlab pods are initiated by a user trigger that spawns a Pod with the requested resources.... and is scaled down once idle)

2022-12-28 11:42 UTC, pavithraes commented on docs/docs/explanations/architecture.mdx
> +to ensure security, redundancy and scalability
```suggestion
to ensure security, redundancy, and scalability.
```

2022-12-28 11:43 UTC, pavithraes commented on docs/docs/explanations/architecture.mdx
> +title: Nebari architecture and conceptual guide
```suggestion
title: Nebari architecture
```

2022-12-28 11:44 UTC, pavithraes commented on docs/docs/explanations/architecture.mdx
> +title: Nebari architecture and conceptual guide
Context: The documentation section where this page lives is called "Conceptual guides", so we needn't say it again explicitely :)

2022-12-28 12:10 UTC, pavithraes commented on docs/docs/explanations/architecture.mdx
> +state.
```suggestion
state.
You can learn more details in the [Kubernetes documentation](https://kubernetes.io/docs/concepts/overview/).
```

2022-12-28 12:19 UTC, pavithraes commented on docs/docs/explanations/architecture.mdx
> +outline the Kubernetes services.
I believe the "Kubernetes services" diagram is the one in the previous section?

```suggestion
Below are diagrams to help show the architecture and design behind
Nebari. The diagrams are meant to show different levels and cloud specific infrastructure.
```

2022-12-28 12:25 UTC, pavithraes approved these changes
(deleted, clicked by approve by mistake!)

2022-12-28 12:26 UTC, pavithraes requested changes
@viniciusdc Thank you for taking over this PR and updating it! It's looking good!

I've shared some small suggestions inline, and have a couple of high-level comments:

- We need to merge the main branch again, and update sidebar.js -- it currently shows "References" twice.
- We can remove the images that aren't being used from this PR.

2023-01-10 16:19 UTC, viniciusdc commented
Self-review: I will remove the unused images from this PR as well as mention the source of one of the terraform images as it comes from their docs (thus needs citation)

2023-01-12 14:07 UTC, pavithraes approved these changes
Thanks for the updates, `@viniciusdc`!

2023-01-12 14:08 UTC, merged