WIP- How to guide on Dask-Nebari config
nebari-dev/nebari-docs pull request #79
Opened 2022-06-30 13:55 UTC by sayantikabanik

resolves #68 

This PR is a work in progress. I am currently referring to [this](https://docs.qhub.dev/en/latest/source/installation/configuration.html?highlight=dask#full-configuration-example) guide to pick bits and pieces.

2022-06-30 14:30 UTC, sayantikabanik commented
@HarshCasper @iameskild feel free to continue on this PR or close it.

2022-07-11 14:33 UTC, iameskild commented
@HarshCasper could you look at [integrating these docs](https://docs.qhub.dev/en/latest/source/installation/configuration.html?highlight=dask#dask-profiles) into this how to guide?

2022-09-14 13:37 UTC, kcpevey requested changes

2022-09-14 13:37 UTC, kcpevey commented on docs/docs/how-tos/dask-nebari-config.md
> +Our main focus in this tutorial will be the `profiles` & `dask_worker` section of the config file.
```suggestion
In this tutorial we will dive into the configuration requirements for running Daask on Nebari. The Nebari config (`qhub_config.yml`) is at the heart of all things (most of them) related to configurations.
Our main focus in this tutorial will be the `profiles` & `dask_worker` section of the config file.
```

2022-09-14 13:37 UTC, kcpevey commented on docs/docs/how-tos/dask-nebari-config.md
> +- Dask scheduler
```suggestion
There are three core configuration components necessary for setting up Dask on Nebari.

These are:
- [Dask-gateway](https://gateway.dask.org/): provides a secure, multi-tenant server for managing [Dask](https://dask.org/) clusters
- [Dask workers](https://distributed.dask.org/en/stable/worker.html): compute tasks as directed by the scheduler and store/serve results
- [Dask scheduler](https://docs.dask.org/en/stable/scheduler-overview.html): executes the task graph by coordinating task distribution
```

2022-09-14 13:37 UTC, kcpevey commented on docs/docs/how-tos/dask-nebari-config.md
> +### Basic infrastructure details
```suggestion
## Basic infrastructure details
```

2022-09-14 13:37 UTC, kcpevey commented on docs/docs/how-tos/dask-nebari-config.md
> +### How to configure dask gateway profiles?
```suggestion
## Configuring Dask Gateway profiles
```

2022-09-14 13:37 UTC, kcpevey commented on docs/docs/how-tos/dask-nebari-config.md
> +```
```suggestion
```

## Next Steps

Now that you have your Nebari instance all set up to run Dask, check out our user guide on [Working with Big Data using Dask](/tutorials/using_dask)!

```

2022-09-14 13:37 UTC, kcpevey commented on docs/docs/how-tos/dask-nebari-config.md
> +```
Just guessing at that link to the page, you should double check that works

2022-09-14 13:37 UTC, kcpevey commented on docs/docs/how-tos/dask-nebari-config.md
> +
```suggestion

The following is an example configuration:
```

2022-09-14 13:37 UTC, kcpevey commented on docs/docs/how-tos/dask-nebari-config.md
> +-  `guarantee`: is the amount of memory the Kubernetes scheduler uses to place a given pod. In general, the `guarantee`  will be less than the limit. Often the node itself has less available memory t
```suggestion
-  `guarantee`: is the amount of memory the Kubernetes scheduler uses to place a given pod. In general, the `guarantee`  will be less than the limit. Often the node itself has less available memory than the node specification. You may want to check out this [guide from digital ocean](https://docs.digitalocean.com/products/kubernetes/#allocatable-memory) which also generally applies to other clouds.
```

2022-09-14 13:37 UTC, kcpevey commented on docs/docs/how-tos/dask-nebari-config.md
> +### How to configure dask scheduler?
```suggestion
## Configuring the Dask Scheduler
```

2022-09-14 13:37 UTC, kcpevey commented on docs/docs/how-tos/dask-nebari-config.md
> +In a few instances, the dask worker node-group might be running on quite a large instance, perhaps with 8 CPUs and 32 GB of memory (or more). In this case, you might also want to increase the resourc
```suggestion
For analyses requiring heavy compute, there may be some situations where the Dask worker node-group might be running on quite a large cluster, perhaps with 8 CPUs and 32 GB of memory (or more). In this case, you might also want to increase the resource levels associated with the Dask scheduler.
```

2022-09-14 13:37 UTC, kcpevey commented on docs/docs/how-tos/dask-nebari-config.md
> +
```suggestion

The following is an example of a Dask worker configuration with the Scheduler resources modified.
```

2022-09-14 13:37 UTC, kcpevey commented on docs/docs/how-tos/dask-nebari-config.md
> +      scheduler_memory: 28G
Is this a jupyterlab profile?

2023-01-20 00:25 UTC, pavithraes commented
The content in this PR is covered in #115. :)

2023-01-20 00:25 UTC, closed without merging